language: node_js
node_js:
 - "node"
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: travis_wait npm install
